services:
  - type: web
    name: aws-exam-prep
    env: python
    pythonVersion: 3.9.0
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true 